# Generated by Django 4.1.3 on 2022-12-05 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoElectronico', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('dni', models.BigIntegerField()),
                ('celular', models.BigIntegerField()),
                ('consulta', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.BigIntegerField()),
                ('precio', models.FloatField()),
                ('peso', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('stripe_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoPago', models.CharField(max_length=255)),
                ('cantidadProducto', models.BigIntegerField()),
                ('total', models.FloatField()),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('apartamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('celular', models.BigIntegerField()),
                ('correo', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=255)),
                ('dni', models.BigIntegerField()),
                ('estadoEntrega', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='informacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('apartamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='carritoDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.BigIntegerField()),
                ('total', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
